Importação das bibliotecas e/ou módulos (packages ou pacotes) necessários.

In [17]:
# Importar as bibliotecas necessárias
import pandas as pd
# https://pandas.pydata.org/

# Conversão de dados categóricos em numéricos
from sklearn.preprocessing import LabelEncoder
# https://scikit-learn.org/stable/modules/preprocessing.html

# Algoritmos de classificação
# KNN (K-Nearest Neighbors)
from sklearn.neighbors import KNeighborsClassifier
# https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

# Decision Tree
from sklearn.tree import DecisionTreeClassifier
# https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html

# Seleção de dados de treino e teste
from sklearn.model_selection import train_test_split
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

# Obtenção da acurácia do modelo
from sklearn.metrics import accuracy_score
# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html

Importação dos dados

https://www.kaggle.com/datasets/shivam2503/diamonds

In [18]:
# Criar um Pandas Data Frame a partir do arquivo de dados csv
dados = pd.read_csv('/content/diamonds.csv')
dados

Unnamed: 0  carat        cut color clarity  depth  table  price     x  \
0               1   0.23      Ideal     E     SI2   61.5   55.0    326  3.95   
1               2   0.21    Premium     E     SI1   59.8   61.0    326  3.89   
2               3   0.23       Good     E     VS1   56.9   65.0    327  4.05   
3               4   0.29    Premium     I     VS2   62.4   58.0    334  4.20   
4               5   0.31       Good     J     SI2   63.3   58.0    335  4.34   
...           ...    ...        ...   ...     ...    ...    ...    ...   ...   
53935       53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75   
53936       53937   0.72       Good     D     SI1   63.1   55.0   2757  5.69   
53937       53938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66   
53938       53939   0.86    Premium     H     SI2   61.0   58.0   2757  6.15   
53939       53940   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83   

          y     z  
0      3.98  2.43  
1      3.84  2.31  
2      4.07  2.31  
3      4.23  2.63  
4      4.35  2.75  
...     ...   ...  
53935  5.76  3.50  
53936  5.75  3.61  
53937  5.68  3.56  
53938  6.12  3.74  
53939  5.87  3.64  

[53940 rows x 11 columns]

Análise Exploratória

In [19]:
# Quantos registros (linhas) e quantos atributos (colunas) tem o Data Frame?
dados.shape

print(f'O conjunto de dados tem {dados.shape[0]} linhas e {dados.shape[1]} colunas.')

O conjunto de dados tem 53940 linhas e 11 colunas.


In [ ]:
# Visualizar as primeiras linhas
dados.head()

In [ ]:
# Visualizar as últimas linhas
dados.tail()

In [ ]:
# Nomes das colunas
dados.columns

In [20]:
# Informações do formato de dados das colunas
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  53940 non-null  int64  
 1   carat       53940 non-null  float64
 2   cut         53940 non-null  object 
 3   color       53940 non-null  object 
 4   clarity     53940 non-null  object 
 5   depth       53940 non-null  float64
 6   table       53940 non-null  float64
 7   price       53940 non-null  int64  
 8   x           53940 non-null  float64
 9   y           53940 non-null  float64
 10  z           53940 non-null  float64
dtypes: float64(6), int64(2), object(3)
memory usage: 4.5+ MB


In [ ]:
# Estatísticas descritivas das colunas numéricas
dados.describe()

In [ ]:
# Estatísticas descritivas das colunas não numéricas
dados.describe(include='object')

cut  color clarity
count   53940  53940   53940
unique      5      7       8
top     Ideal      G     SI1
freq    21551  11292   13065

In [ ]:
# Seleção dos dados de uma coluna (formato Series)
preco_series = dados['price']
preco_series

In [ ]:
# Seleção dos dados de uma coluna (formato Data Frame)
preco_df = dados[['price']]
preco_df

In [ ]:
type(preco_df)

In [ ]:
# Cálculo de média aritmética dos valores de uma coluna
media_aritm = dados['price'].mean().round(4)
media_aritm

In [ ]:
# Cálculo de mediana dos valores de uma coluna
mediana = dados['price'].median().round(4)
mediana

In [ ]:
# Cálculo do desvio padrão dos valores de uma coluna
desvio_padrao = dados['price'].std().round(4)
desvio_padrao

Pré Processamento

In [ ]:
dados.head()

In [22]:
# Exclusão de uma coluna usando o método .drop
# axis = 0 ----> linha
# axis = 1 ----> coluna
dados = dados.drop('Unnamed: 0', axis=1)
dados

carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [ ]:
# Conversão dos dados de uma coluna em um Array Numpy (Vetor)
vetor_numpy = dados['price'].values
vetor_numpy

In [23]:
# Conversão de uma coluna de valores categóricos para numéricos
# Label Encoding
le = LabelEncoder()

In [24]:
dados['cut'].values

array(['Ideal', 'Premium', 'Good', ..., 'Very Good', 'Premium', 'Ideal'],
      dtype=object)

In [25]:
dados['cut'] = le.fit_transform(dados['cut'])


In [26]:
dados['cut'].values

array([2, 3, 1, ..., 4, 3, 2])

In [27]:
dados.head()

carat  cut color clarity  depth  table  price     x     y     z
0   0.23    2     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    3     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23    1     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    3     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31    1     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [28]:
# Separação dos dados de entrada e dados de saída
# X maiúsculo ----> Dados de entrada / Features / Variáveis independentes
# y minúsculo ----> Dados de saída / Target (alvo) / Variável dependente
# dados.iloc[linhas, colunas]
X = dados.iloc[:, 7:] # Todas as linhas e as colunas de 7 a 9.
X.head()

x     y     z
0  3.95  3.98  2.43
1  3.89  3.84  2.31
2  4.05  4.07  2.31
3  4.20  4.23  2.63
4  4.34  4.35  2.75

In [29]:
X.values

array([[3.95, 3.98, 2.43],
       [3.89, 3.84, 2.31],
       [4.05, 4.07, 2.31],
       ...,
       [5.66, 5.68, 3.56],
       [6.15, 6.12, 3.74],
       [5.83, 5.87, 3.64]])

In [31]:
# Dados de saída
y = dados['cut'].values
y

array([2, 3, 1, ..., 4, 3, 2])

In [ ]:
# Separação em dados de treino e dados de teste
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
# SEED
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=10)
X_train

Escolha do algoritmo

In [53]:
# Instanciar o modelo
my_model = KNeighborsClassifier()

In [54]:
# Treinar o modelo
my_model.fit(X_train, y_train)

KNeighborsClassifier()

In [55]:
# Realizar as predições
y_predict = my_model.predict(X_test)
y_predict

array([3, 1, 4, ..., 3, 2, 2])

In [56]:
y_test

array([3, 4, 4, ..., 2, 3, 3])

In [57]:
# Calcular a acurácia
acuracia = 100 * (accuracy_score(y_test, y_predict))
print(f'A acurácia do modelo baseado no algoritmo KNN é de {acuracia: .2f} %')

A acurácia do modelo baseado no algoritmo KNN é de  60.68 %


EXERCÍCIO: Treine um outro modelo usando o algoritmo Decision Tree e compare as métricas